services:
  - type: web
    name: lottery-api
    env: php
    buildCommand: composer install
    startCommand: php -S 0.0.0.0:$PORT -t public/
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
