services:
  # Static frontend
  - type: web
    name: 2d3d-lottery
    env: static
    buildCommand: npm install
    staticPublishPath: ./public
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # API backend
  - type: web
    name: 2d3d-lottery-api
    env: php
    buildCommand: composer install
    startCommand: heroku-php-apache2 public/
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: 2d3d-lottery-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: 2d3d-lottery-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: 2d3d-lottery-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: 2d3d-lottery-db
          property: password

databases:
  - name: 2d3d-lottery-db
    plan: free
