services:
  # Backend API Service
  - type: web
    name: lottery-api
    env: docker
    dockerfilePath: ./Dockerfile
    region: singapore
    plan: starter
    healthCheckPath: /api/health
    envVars:
      - key: DB_HOST
        value: sql12.freesqldatabase.com
      - key: DB_NAME
        value: sql12753941
      - key: DB_USER
        value: sql12753941
      - key: DB_PASS
        value: xPMZuuk5AZ

  # Frontend Service
  - type: web
    name: lottery-frontend
    env: docker
    dockerfilePath: ./Dockerfile.frontend
    region: singapore
    plan: starter
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_URL
        fromService:
          name: lottery-api
          type: web
          property: url
    buildCommand: npm run build
    startCommand: nginx -g 'daemon off;'
    autoDeploy: true
