services:
  - type: web
    name: 2d3d-lottery
    env: php
    buildCommand: composer install
    startCommand: heroku-php-apache2 public/
    healthCheckPath: /health.php
    envVars:
      - key: PHP_VERSION
        value: 8.1
