services:
  - type: web
    name: 2d3d-lottery
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      mkdir -p storage/logs
      chmod -R 777 storage
    startCommand: heroku-php-apache2 public/
    healthCheckPath: /health.php
    envVars:
      - key: PHP_VERSION
        value: 8.1
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://twod3d-lottery.onrender.com
    staticPublishPath: ./public
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000
      - path: /*
        name: Content-Security-Policy
        value: "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' https: data:;"
